### ISSUE TITLE
[12.0] pos_margin doesn't handle inclued/excluded taxes

### ISSUE THREAD

**Issue by gregory-moka** [OCA/margin-analysis#108]
Hello,
I've got a strange behaviour on `pos_margin` addon.

**The case :**
I have a product that 

- I buy 28,8€ tax included, 
- I sell it 32€ tax included
- The margin rate is 10%
- The margin is 3,2€

When I set the product with all excluded taxes, all seems ok : 

**General informations :** 

![image](https://user-images.githubusercontent.com/45974412/133090028-e46df496-05ac-40aa-a55d-11629b5e17cc.png)

**Purchase tab :**

![image](https://user-images.githubusercontent.com/45974412/133090161-248da80d-212d-4a1e-85cb-0ef49b75d8ef.png)

But, as soon as set the prices with included taxes, all is going weird : 

**General informations :** 

![image](https://user-images.githubusercontent.com/45974412/133090340-d0d86587-0e77-46fa-8033-c7930825e04a.png)

**Purchase tab :**

![image](https://user-images.githubusercontent.com/45974412/133090404-37357360-57b0-4f78-bc5f-b3199f8447b1.png)

Is their something that I don't catch on the addon settings, or the addon is mainly done for exluded taxe sales ?
Thank you for help 😄

Copy of : https://github.com/OCA/pos/issues/707

**Comment by legalsylvain** [comment]
As Said on the other pr, could you make a test on runbot and send the link ?
Kind regards.

**Comment by gregory-moka** [comment]
I'm on it :)
http://3502006-12-0-e11efc.runbot1-3.odoo-community.org/web

**Comment by gregory-moka** [comment]
Reproduced : 
![image](https://user-images.githubusercontent.com/45974412/133117578-8c3dbbb7-f49a-43d5-9028-f8c992e262f0.png)
[Product](http://3502006-12-0-e11efc.runbot1-3.odoo-community.org/web#id=39&action=247&model=product.product&view_type=form&menu_id=118)

**Comment by legalsylvain** [comment]
I get it, I think.

- The sale price depend on the VAT.
- the cost price is allways vat excl.

so, in your case : 
- sale price = 32€ vat incl, = 26,67€ Vat excl. (32€ / (1 + 20%))
- cost price = 28,80€ vat excl.

margin = 26,67 - 28,80 = -2,13€
margin (%) = -2,13€ / 26,67 = -8%

Le compte est bon.

So, in my configuration : 
for B2B company, I work with purchase tax vat excl and  sale tax vat excl
for B2C company, I work with purchase tax vat excl and  sale tax vat incl

in all case, I select purchase tax vat excl. I never saw valid use case where purchase tax is vat incl).

Hope it help.
Kind regards.

**Comment by gregory-moka** [comment]
Indeed, it helps, and I saw that cost is tax excl (28,8€ tax incl is 24€ tax excl, and it works with this value).
But, I work with customers that always talk about prices tax included, cause, most of the time, the Vat is not applied (specific situation).

So, I will explain that cost is always tax excluded. I'll guess that I'll have to propose to change the cost field's name to Odoo SA ot at least, change the translation.

Other question. This add-on is working with standard price cost method, does it works with FIFO and AVCO methods ?

**Comment by legalsylvain** [comment]
>  the Vat is not applied (specific situation)

what is the situation ? autoentrepreneur ? association ?

> This add-on is working with standard price cost method, does it works with FIFO and AVCO methods ?

You are talking about ``pos_margin`` this time, I guess ;-). The module works as Odoo standard module ``sale_margin`` works.

**Comment by legalsylvain** [comment]
Note regarding maintainers : this issue can be closed.

**Comment by gregory-moka** [comment]
> what is the situation ? autoentrepreneur ? association ?

Administration (some of them are not VAT concerned), association under a revenue limit, and, in some cases, VAT is not applyed on sale price but on margin (we already worked on this last point).

> You are talking about `pos_margin` this time, I guess ;-). The module works as Odoo standard module `sale_margin` works.

Ok :)
(I closed this issue. Thanks for your answers.
