### ISSUE TITLE
[14.0] sale_margin_security: group in python fields

### ISSUE THREAD

**Issue by rafamarpe** [OCA/margin-analysis#128]
**Is your feature request related to a problem?**
If so, please provide clear and concise description of what the problem is.
A user without the "Show Sales Margin" permission can see the margin in the sales report

**Describe the solution you'd like**
If you don't have the "Show Sales Margin" permission you can't see the margin in the report

**Describe alternatives you've considered**
Restrict visibility by security groups at the python level in the sale.report model.

**Additional context**
Add any other context about the feature request here.

**Comment by pedrobaeza** [comment]
The module is not yet migrated, so you can't put an issue about something not migrated. If you are migrating the module, put it on the ROADMAP, or if it's something that should work for the migration, ask for help in the PR.

**Comment by rafamarpe** [comment]
Ok, @pedrobaeza, I tagged it as an improvement to see if the functionality was viable.
Thanks
