### ISSUE TITLE
Automatic tests and Pylint are not passing and in 7.0

### ISSUE THREAD

**Issue by clonedagain** [OCA/margin-analysis#13]
Several modules have failing tests or pylint issues: https://travis-ci.org/OCA/margin-analysis/jobs/40980110
- product_price_history
  - [ ] PyLint https://travis-ci.org/OCA/margin-analysis/jobs/40980110#L150
- product_get_cost_field
  - [ ] **cost_price_update.yml** https://travis-ci.org/OCA/margin-analysis/jobs/40980110#L194
- product_historical_margin
  - [ ] PyLint https://travis-ci.org/OCA/margin-analysis/jobs/40980110#L155
  - [ ] basic_historical_margin.yml https://travis-ci.org/OCA/margin-analysis/jobs/40980110#L261
- product_price_history
  - avg_price_computation_mutlicompanies_multicurrencies.yml
    - [ ] https://travis-ci.org/OCA/margin-analysis/jobs/40980110#L349
    - [ ] https://travis-ci.org/OCA/margin-analysis/jobs/40980110#L355
- product_cost_incl_bom
  - [ ] **cost_price_empty_phantom_bom.yml** https://travis-ci.org/OCA/margin-analysis/jobs/40980110#L425
- product_cost_incl_bom_price_history
  - [ ] PyLint https://travis-ci.org/OCA/margin-analysis/jobs/40980110#L158

**Comment by clonedagain** [comment]
I'm willing to help with this, but I'll probably need help from the authors. Is anyone available?

**Comment by pedrobaeza** [comment]
For pylint, we have #11 that I have to complete.

**Comment by clonedagain** [comment]
OK nice. I'm most worried by the failing tests in product_get_cost_field and product_cost_incl_bom, they seem to indicate a wrong calculation.
@gurneyalex @yvaucher @jgrandguillaume @guewen: can one of you comment please?

**Comment by jgrandguillaume** [comment]
Hi,

I just saw that in the first place some field are not anymore here in v 8:

For https://travis-ci.org/OCA/margin-analysis/jobs/40980110#L194:

picking_policy in SO
supply_method in product

=> I suggest to remove the supply_method value for product as it makes non-sense in v8 + add picking_policy by default as it is now required.

May be it is just for that that the test break.

Can you please make a PR to correct first the data recording for the test ? If you do that job, we'll see if we still have trouble in the test scenario and computation of prices.

By the way, note that in v 8, there is a price history table already. We might think of adapting this module to adopt this new table... I don't have time to check that yet... But it might be a good way to go on with this module.

My2Cents,

Joël

**Comment by clonedagain** [comment]
Thanks @jgrandguillaume I'll give it a try on Friday if I can.

**Comment by clonedagain** [comment]
The Travis log is full of errors and still it marks the branch 7.0 "build passing".
    https://travis-ci.org/OCA/margin-analysis/jobs/42406339
Is Travis drunk?

**Comment by clonedagain** [comment]
I'm clueless about supply_method: why does the log say there was a not-null constraint violated? If I add a supply_method field I get `<openerp.osv.orm.product.product object at 0x52b8f10>' does not contain field 'supply_method'`. That's normal since procurement is not installed.

Ideas ?

**Comment by yvaucher** [comment]
@clonedagain False positive has been fix here: https://github.com/OCA/maintainer-quality-tools/commit/25868a975f99a23dbb430b089d2b5163b7740dd8

**Comment by laetitia-gangloff** [comment]
Hello,

I have some question about test : avg_price_computation_mutlicompanies_multicurrencies.yml in product_price_history module.

I have never used currency so it is difficult to understand for me.

I am sure there is one bug in the method _get_transaction_company_id (I will do a PR for this), we need to check "force_company" before checking "company_id".

And for the failing test, I have the feeling it is an odoo bug, I didn't understand why the first time it stores the standard price, it didn't use currency.
