### ISSUE TITLE
sale_margin_security still leak the margin field in Pivot View [V15]

### ISSUE THREAD

**Issue by hitrosol** [OCA/margin-analysis#157]
One of the reason to have sale_margin_security is to prevent some users to see the margin in the sales order, but the field is still appear in the pivot view of sale_order.

## Module
sale_margin_security

## To Reproduce
**Affected versions**: V12, V13, V14, V15

1. Install the sale_margin_security
2. Don't click the option in the user config
3. Open the Sale Order, change the view to be Pivot View
4. Click the measure and Margin field is still there
![image](https://user-images.githubusercontent.com/5949936/204957156-e6678511-2316-47d2-b24e-74f3a388cd40.png)

**Expected behavior**
The field margin is also hidden if the user is not checked the Show Sale Margin option.

**Comment by pedrobaeza** [comment]
I think that on old versions, this one will be difficult to be fixed, as pivot views don't allow groups on measures. Can you please try?
