### ISSUE TITLE
product_standard_margin: Deprecated call to decimal_precision.get_precision [15.0]

### ISSUE THREAD

**Issue by jans23** [OCA/margin-analysis#166]
When installing product_standard_margin for 15.0 for the first time I see the following warning several times:

`WARNING odoo odoo.addons.base.models.decimal_precision: Deprecated call to decimal_precision.get_precision(<application>), use digits=<application> instead`

I don't know if this is really an issue but it would be good to avoid such warnings to avoid any doubts and confusion.

**Comment by legalsylvain** [comment]
Hi. Thanks for reporting. Could you make a PR ? Thanks !

**Comment by nikunjantala** [comment]
Here is the PR for fix : https://github.com/OCA/margin-analysis/pull/170
