### ISSUE TITLE
Bug on product_margin_classification when variants product not activated on DB

### ISSUE THREAD

**Issue by vdewulf** [OCA/margin-analysis#180]
## Module
product_margin_classification

## Describe the bug

When selecting a product margin classification on a product form, the field is empty when saving manually (and if we don't save manually as not required on v16, the field is empty when moving to another screen).

## To Reproduce
**Affected versions**: v16

1. Install module, create a margin classification in the configuration
2. Go on a product form (product.template) and select a value on the product margin classification field
3. Save => the field is empty (no error is displayed)

**Expected behavior**
3. Save => the field keeps the value selected by user

**Additional context**
We investigated the issue with a developer in our team @huguesdk. Issue comes from the fact that the value of this field on the product.template is overwritten by the value on the product.product.
We think that in case there is no variants products on the database (hence 1 product.product for 1 product.template), the field should be exactly the same on both models (like the field pricelist for example).

We might propose a PR to fix this in the following months depending on the need of this module for our customers in v16.
@legalsylvain fyi

**Comment by huguesdk** [comment]
@legalsylvain has this been correctly fixed by #181?

**Comment by vdewulf** [comment]
I tested on runboat on v16.

Steps to reproduce the behavior:

    Install module, déactivate variants, create a margin classification in the configuration
    Go on a product form (product.template) and select a value on the product margin classification field
    Save => the field keeps the value selected by user
OK

**Comment by vdewulf** [comment]
fixed
