### ISSUE TITLE
Bug in account_invoice_margin

### ISSUE THREAD

**Issue by LuqueDaniel** [OCA/margin-analysis#52]
If you create an invoice without the **Show Invoice Margin** security group, the `purchase_price` field of `account.invoice.line` model isn't set.

**Steps to reproduce**:
1. With a user who doesn't have **Show Invoice Margin** permission
2. Create an invoice
3. Give permissions to the user to see the margins (Show Invoice Margin)
4. Press `ctrl+r` to reload
5. Check the invoice line. The margin percentage will be 100% and the cost will be 0.

![imagen](https://user-images.githubusercontent.com/1286535/62966270-fb7f0e80-be06-11e9-8854-be7f63e2cb29.png)

Can it be related to the way the view is restricted to the group?

https://github.com/OCA/margin-analysis/blob/366c90b2f54901f4aff25098fb6a011f2adc4b2a/account_invoice_margin/views/account_invoice_margin_view.xml#L24-L25

**Comment by pedrobaeza** [comment]
Odoo version?

**Comment by LuqueDaniel** [comment]
Version 11.0.20190812 and runbot.

**Comment by pedrobaeza** [comment]
@sergio-teruel can you check this?

**Comment by pedrobaeza** [comment]
Fixed in #64
