### ISSUE TITLE
[12.0] Some questions regarding the margin Odoo+OCA

### ISSUE THREAD

**Issue by victoralmau** [OCA/margin-analysis#78]
I have some general doubts regarding the calculation of the margin that I am not very clear if it is the operation of the Odoo margin, what has been implemented in this repository and / or if some improvements can be made to calculate it.

**How Odoo works**
To calculate the margin in the sale_order, use the "_standar_price_" field in the products, which can be defined as an always fixed value (OK) or according to the category of products that this field changes (property_cost_method=real and property_valuation=real_time) according to all stock movement operations (making price averages)

[**IDEA**] Clarify that I think there should be a check at the product level (by default True) to define if you want to control the margin of that product in sales)

**Margin calculation errors**
Using the "_standar_price_" field of each product (calculated or not) does not seem correct to me, since the inventory valuation cost of the stock movements that "have come out" of the "stock_picking" linked to the "should be used" sale_order "in question. This clarification is very important, since even if the FIFO method is used and Odoo "reserves" the stock units that are going to come out, this does NOT mean that those actually come out (for example, if working in lots, it will be highly recommended in many cases that all the units of each product in the stock_picking are from the same lot). This clarification would (from my point of view) cause the margin to have to be calculated when the stock_picking is Done.

[**IDEA**]In addition to the above, I believe that there should be a cron that is run 1 time a month (for example) or manually to recalculate the margin of all orders since if "stock_landed_cost" have been created the cost per unit will be different from previously defined (generally the stock_landed_cost are created days after the merchandise has entered the warehouse and therefore units of that merchandise have already left).

**Idea to define purchase_price of shipping order line according to cost of the delivery carrier**
Finally, I think that it would also be a very interesting contribution, to be able to define the "real" cost of the shipments (if the shipment is made with external companies and we use the addon https://github.com/OCA/delivery-carrier/ tree / 12.0 / _base_delivery_carrier_label_ as the base for integrations with each carrier, a "purchase_price" should be defined there) so that this cost is defined as "purchase_price" of the sale_order transport line (by default the purchase_price of that line would be 0 , if it is changed to 10, the margin of that line changes, therefore the total margin of the order and if we have defined the margin in the invoices as well). For this to work, an addon (one base and the other for each integration with each carrier) would be necessary so that we can attach the file (.xls, .txt, etc.) that the transport company gives us regarding each purchase invoice with all the "shipments" you charge us (and the cost of each one of them).

Sorry for so many questions and mixing so many topics, but it is a problem-solution that has happened to us and we do not know if ODOO + OCA provide a solution to all this and / or how.
In case some of these topics are not thought of in Odoo and can be developed in OCA, I would be delighted to help you with it.

A greeting.

**Comment by pedrobaeza** [comment]
I think you are talking about landed costs. In v13, official `stock_landed_cost` serves also for AVCO, and in <=v12 we have in OCA `purchase_landed_cost`.

**Comment by victoralmau** [comment]
Ok, thanks, I think from the repository https://github.com/OCA/margin-analysis some addons:

- account_invoice_margin
- account_invoice_margin_sale
- sale_margin_sync
- sale_order_margin_percent

They would solve almost all my questions.


Regarding "Idea to define purchase_price of shipping order line according to cost of the delivery carrier" yes, the purchase_landed_cost addon would help with this, although normally the problem is that you do not have an invoice with all the lines of each shipment (and although If the manual process existed, it would be so long that it would not help), but, I will consider that addon as a base to "import" an .xls / .csv with the list of shipments and thus be able to define the cost of each picking and be able to define it in the line of the corresponding order.

Thank you very much.
